name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci-result:
    name: CI Result
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: All checks passed
        run: echo "CI Result passed."
