name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions: {}

jobs:
  ci-result:
    name: CI Result
    runs-on: ubuntu-24.04
    if: always()
    permissions: {}
    steps:
      - name: All checks passed
        run: echo "CI Result passed."
